### ISSUE TITLE
Manual edit monster list, figurines and collectors book (PC)

### ISSUE THREAD

**Issue by dbustosm** [Meth962/SymphoniaSaveEdit#10]
Hi @Meth962 @wingedcatgirl,

I add a 100% manual edits for monster list, figurine and collectors book.

 "MonsterList":[0x09,0x01,0x01,0x09,0x01,0x4D,0x05,0x49,0x01,0x01,0x05,0x05,0x01,0x01,0x09,0x45,0x01,0x11,0x0D,0x0D,0x01,0x0D,0x05,0x01,0x01,0x0D,0x05,0x09,0x01,0x3F,0x0D,0x01,0x0D,0x05,0x01,0x05,0x4D,0x01,0x01,0x05,0x45,0x01,0x01,0x05,0x81,0x45,0x41,0x41,0x41,0x4D,0x41,0x4D,0x45,0x45,0x01,0xC5,0x09,0x4D,0x4D,0x01,0x01,0x01,0x0D,0x3F,0x05,0x01,0x4D,0xC5,0x0D,0x01,0x0D,0xCD,0x05,0x85,0x4D,0xC1,0xC5,0x01,0x01,0x01,0x05,0x09,0x0D,0x05,0x0D,0x0D,0x0D,0x01,0x0D,0x05,0x05,0x0D,0x0D,0x01,0x0D,0x01,0x0D,0x05,0x05,0x05,0x05,0x05,0x41,0x05,0x05,0x01,0x05,0x01,0x05,0x01,0x01,0x4D,0x45,0x0D,0x01,0x4D,0x05,0x4D,0xC5,0x45,0x01,0x0D,0x01,0x05,0x45,0x0D,0x45,0x01,0x01,0x01,0x05,0x01,0x05,0x01,0x0D,0x45,0x5D,0x09,0x45,0x05,0x01,0x4D,0x0D,0x01,0x45,0x0D,0x0D,0x01,0x01,0x4D,0x01,0x0D,0x01,0x01,0x05,0x85,0x01,0x05,0x01,0x0D,0x01,0x0D,0x0D,0x05,0x05,0x01,0x01,0x01,0x4D,0x01,0x45,0x01,0x05,0x81,0x01,0x01,0x3F,0x05,0x25,0xAD,0x45,0x01,0x05,0x01,0x8D,0x95,0x45,0x0D,0x01,0x05,0x0D,0x41,0x05,0x05,0x01,0x85,0x05,0x05,0x05,0x45,0x85,0x05,0x85,0x05,0x05,0x85,0x05,0x05,0x05,0x05,0x05,0x3F,0x3F,0x3F,0x3F,0x01,0x0D,0x0D,0x01,0x25,0x05,0x01,0x4D,0x45,0x05,0x05,0x05,0x3F,0x25,0x01,0x3F,0x3F,0x3F,0x3F,0x0D,0x01,0x01,0x81,0x0D,0x01,0x01,0x0D,0x21,0x05,0x0D,0x05,0x05,0x01,0x0D,0x0D,0x01,0x01,0x01,0xC5,0x01,0x05,0x85]

**Comment by dbustosm** [comment]
Figurine book 100%:
"FigurineBook":[0x00,0x00,0x00,0x00,0xEC,0x04,0x00,0x00,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF]

**Comment by dbustosm** [comment]
"CollectorsBook":[0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF],

**Comment by Meth962** [comment]
Thank you, @dbustosm ! I added your lists in as a button "fill figurine/monster/collector books".
Also it will now remember your last loaded save type, so it should not default to unwanted save types.
Released here: [v0.9.3](https://github.com/Meth962/SymphoniaSaveEdit/releases/tag/v0.9.3)
