### ISSUE TITLE
Ps4 compatible save editor

### ISSUE THREAD

**Issue by jenovamaster** [Meth962/SymphoniaSaveEdit#5]
Hello, is it possible to make the Tales of Symphonia save editor compatible for the PS4 version?  Thanks a lot

**Comment by Meth962** [comment]
Thanks to a great user that goes by Noxbur, I was able to work with him and find the way to make this work on raw PS4 saves. An update will be coming to do so. It will only work if you can decrypt the saves yourself.

The PS4 version matches the Switch in terms of bytes, except for the PS4 version put back the old Gamecube checksum at the top of the game (one of two checksums really). However, they did it wrong and counted short 28 bytes, but big thanks to Noxbur for testing with his PS4 over and over and over again, we finally found it!

**Comment by Meth962** [comment]
This is now confirmed to work with PS4 unencrypted files! :)
I don't think PS4 encryption has been figured out, so I can't have it decrypt like the PS3 does yet.
However determined users have found ways to make the consoles give the raw file :)
